sudo: requires 

services: 
 - docker

language: python

install: |
  set -x
  git rev-parse HEAD
  sudo -E bash -x ./plancton-bootstrap to-infn/dev || true

script: |
  set -ex
  PREFIX=/opt/plancton/.plancton
  dielog() {
    sudo cat $PREFIX/log/plancton.log
    exit 1
  }
  ls -lR $PREFIX || true
  sudo test -f $PREFIX/plancton.pid || dielog
  sudo kill -0 $(sudo cat $PREFIX/plancton.pid) || dielog
