sudo: requires

services:
 - docker

language: python

install: |
  set -x
  git rev-parse HEAD
  sudo pip install -e .
  sudo plancton-bootstrap mconcas/plancton-conf:travis-test
  sudo planctonctl start

script: |
  set -ex
  PIDFILE=/var/run/plancton.pid
  dielog() {
    sudo cat /var/log/plancton/plancton.log
    return 1
  }
  ls -l $PIDFILE || true
  sudo test -f $PIDFILE || dielog
  sudo kill -0 $(sudo cat $PIDFILE) || dielog
  sudo planctonctl drain
  sleep 40
  sudo grep -qi "no new containers will be started" /var/log/plancton/plancton.log || dielog
  sudo planctonctl resume
  [[ ! -e /var/run/plancton/drain ]]
