#! /bin/bash
export Daemondir="/opt/plancton"
export Rundir="$Daemondir/git/run"
export Daemonuser="plancton"
export Configrepo="https://github.com/mconcas/plancton-conf"

MANUAL_DOCKER_ENABLE=no
MANUAL_DOCKER_START=no
MANUAL_DOCKER_INSTALL=no

function welcome() {
   echo
   echo "<< Welcome to \"Plancton, an opportunistic computing project\" installation procedure >>"
   echo
}

function testcmd() {
   command -v "$@" > /dev/null 2>&1
}

function testreq() {
   echo "Testing requisites..."
   for i in "$@"; do
      if ! testcmd "$i"; then
         echo -e "\e[1;91m !! $i is MISSING !! \e[0;0m"
         exit 1
      else
         echo -e "\e[1;32m !! $i FOUND !! \e[0;0m"
      fi
   done
}

function main() {
   conf_branch="$1"
   if [[ "$conf_branch" == '' ]]; then
      echo -e "\e[1;91mPlease specify the configuration branch to use.\e[m"
      echo -e "\e[1;91m Examples:\e[m"
      echo -e "\e[1;91m\t* to-infn/dev\e[m"
      echo -e "\e[1;91m\t* cern-openstack/dev\e[m"

      exit 1
   fi

   [[ $(id -u) != "0" ]] && echo -e "\e[1;91m [FATAL] Run this script as root.\e[m" && exit 1;

   welcome
   testreq git
   if ! testcmd docker; then
      echo "docker-engine not found, installing from script"
      if ! (curl -sSL https://get.docker.com/ | sh); then
         echo "[WARNING] You have to install docker-engine manually"
         MANUAL_DOCKER_INSTALL=yes
         exit 1
      fi
   fi
   echo "Restarting Docker daemon"
   service docker stop > /dev/null 2>&1
   if ! service docker start; then
      echo "[WARNING] Could not restart. Do it manually with:\n\t sudo service docker stop\n\t sudo service docker start"
      MANUAL_DOCKER_START=yes
   fi

   (
      set -e
      echo "Enabling docker daemon"
      systemctl enable docker > /dev/null 2>&1 ||
      (chkconfig docker --add && chkconfig docker on) > /dev/null 2>&1 ||
      update-rc.d docker defaults > /dev/null 2>&1 ||
      rc-update add docker default > /dev/null 2>&1 ||
      ( echo "Could not enable. Enable it manually" && MANUAL_DOCKER_ENABLE=yes )
      echo "Adding group docker"
      (getent group docker || groupadd docker) > /dev/null 2>&1
      echo "Adding $Daemonuser..."
      id $Daemonuser > /dev/null 2>&1 || useradd -d $Daemondir -g docker $Daemonuser > /dev/null 2>&1
      echo "Adding cronjobs for plancton"
      echo "@reboot /opt/plancton/git/run/plancton-start > /tmp/cron-plancton.log" >> /tmp/tempcron
      echo "@daily /opt/plancton/git/run/plancton-start > /tmp/cron-plancton.log" >> /tmp/tempcron
      crontab -u $Daemonuser /tmp/tempcron
      rm /tmp/tempcron; mkdir -p $Daemondir
      chown -R $Daemonuser $Daemondir
      if [[ "$MANUAL_DOCKER_INSTALL" == "yes" ]]; then
         echo -e " \e[1;91m * Install docker-engine manually\e[m"
         false
      elif [[ "$MANUAL_DOCKER_START" == "yes" ]]; then
         echo -e " \e[1;91m * start/restart docker manually\e[m"
      elif [[ "$MANUAL_DOCKER_ENABLE" == "yes" ]]; then
         echo -e " \e[1;33m * Enable docker daemon manually\e[m"
      fi
   )
   if [[ $? != 0 ]]; then
     echo -e "\e[1;91mLast step has failed\e[m"
     exit 1
   fi

   su $Daemonuser -c "mkdir -p $Daemondir/.plancton"
   echo "Cloning Plancton configuration repository: $conf_branch"
   [[ ! -d $Daemondir/.plancton/conf/.git ]] && su $Daemonuser -c "git clone -b $conf_branch $Configrepo $Daemondir/.plancton/conf"
   echo "Parsing apparmor profile..."
   set +e
   apparmor_parser -r $Daemondir/.plancton/conf/docker-cvmfs
   set -e
   (
   echo "Applying eventual further docker configurations..."
   set +e
   [[ -f $Daemondir/.plancton/conf/docker-config.sh ]] && source $Daemondir/.plancton/conf/docker-config.sh
   set -e
   echo "done."
   )
   echo "running Plancton start script ..."
   su $Daemonuser -c $Daemondir/git/run/plancton-start
}

# Entry point
main "$1"
