#!/bin/bash

export Daemondir="/opt/plancton"
export Daemonuser="plancton"

echo "Killing daemon"
[[ -f $Daemondir/.plancton/plancton.pid ]] && kill $(cat $Daemondir/.plancton/plancton.pid)
rm -Rf $Daemondir

echo "Removing cronjobs to plancton's crontab"
rm -Rf /var/spool/cron/plancton

echo "Deleting $Daemonuser user"
userdel $Daemonuser
