#!/bin/bash -xe

function main() {
   [[ "$USER" != 'plancton' ]] && echo "Run this command as plancton." && exit 1
   echo "-------------------------"
   echo "| Plancton start called |"
   echo "-------------------------"
   planctonctl start
   return $?
}

main
