#!/bin/bash -xe

function main() {
   [[ "$USER" != 'plancton' && $(id -u) != "0" ]] && echo "Run this command as plancton or root." && exit 1
   echo "-------------------------"
   echo "| Plancton start called |"
   echo "-------------------------"
   planctonctl start
   return $?
}

main
