#!/bin/bash

function main() {
   [[ "$USER" != 'plancton' ]] && echo "Run this command as plancton." && exit 1
   echo "-------------------------"
   echo "|Plancton status called.|"
   echo "-------------------------"

   planctonctl status

   return $?
}
main
